server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /


logging.level.root: WARN
logging.level.com.tencent.wxcloudrun: TRACE

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

aep.productId: 15194666

aep.deviceId1:
  imei: 863882045830350
  id: f5b863309e2e4ac1aba126501132bde4

aep.deviceId2:
  imei: 863882045830368
  id: f3cc7f06954a494c83672a4f928930c4

aep.deviceId3:
  imei: 863882045830376
  id: 7ade66ac38d146558c79bd21205befb2